services:
  IntelliChoice:
    image: intellichoice:latest
    container_name: IntelliChoice
    hostname: main
    environment:
      - OPENAI_API_BASE=
      - OPENAI_API_KEY=
      - DB_HOST=mysql
      - REDIS_HOST=redis
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:latest
    container_name: MySQL
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=school
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./database:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: Redis
    hostname: redis